In [5]:
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN

In [6]:
df=pd.read_csv("tel_churn.csv")
df.head()

Unnamed: 0  age  dependents  monthly_charges  total_charges  churn_status  \
0           0   42           3            41.40         595.21             0   
1           1   76           1            46.20         940.05             0   
2           2   39           2            43.05         919.62             0   
3           3   74           3            23.01         538.68             1   
4           4   30           3            38.19         875.93             0   

   call_duration_minutes  gender_Female  gender_Male  marital_status_Married  \
0                   1062              0            1                       1   
1                    901              1            0                       0   
2                    928              1            0                       1   
3                    479              1            0                       0   
4                    650              0            1                       1   

   ...  online_backup_No  online_backup_Yes  device_protection_No  \
0  ...                 1                  0                     1   
1  ...                 1                  0                     1   
2  ...                 0                  1                     1   
3  ...                 0                  1                     0   
4  ...                 1                  0                     0   

   device_protection_Yes  tech_support_No  tech_support_Yes  streaming_tv_No  \
0                      0                0                 1                0   
1                      0                0                 1                0   
2                      0                1                 0                0   
3                      1                1                 0                1   
4                      1                1                 0                1   

   streaming_tv_Yes  streaming_movies_No  streaming_movies_Yes  
0                 1                    0                     1  
1                 1                    1                     0  
2                 1                    1                     0  
3                 0                    0                     1  
4                 0                    1                     0  

[5 rows x 31 columns]

In [7]:
df=df.drop('Unnamed: 0',axis=1)

In [8]:
df.head(5)

age  dependents  monthly_charges  total_charges  churn_status  \
0   42           3            41.40         595.21             0   
1   76           1            46.20         940.05             0   
2   39           2            43.05         919.62             0   
3   74           3            23.01         538.68             1   
4   30           3            38.19         875.93             0   

   call_duration_minutes  gender_Female  gender_Male  marital_status_Married  \
0                   1062              0            1                       1   
1                    901              1            0                       0   
2                    928              1            0                       1   
3                    479              1            0                       0   
4                    650              0            1                       1   

   marital_status_Single  ...  online_backup_No  online_backup_Yes  \
0                      0  ...                 1                  0   
1                      1  ...                 1                  0   
2                      0  ...                 0                  1   
3                      1  ...                 0                  1   
4                      0  ...                 1                  0   

   device_protection_No  device_protection_Yes  tech_support_No  \
0                     1                      0                0   
1                     1                      0                0   
2                     1                      0                1   
3                     0                      1                1   
4                     0                      1                1   

   tech_support_Yes  streaming_tv_No  streaming_tv_Yes  streaming_movies_No  \
0                 1                0                 1                    0   
1                 1                0                 1                    1   
2                 0                0                 1                    1   
3                 0                1                 0                    0   
4                 0                1                 0                    1   

   streaming_movies_Yes  
0                     1  
1                     0  
2                     0  
3                     1  
4                     0  

[5 rows x 30 columns]

In [9]:
#Creating x and y variable

In [10]:
x=df.drop('churn_status',axis=1)
x

age  dependents  monthly_charges  total_charges  call_duration_minutes  \
0     42           3            41.40         595.21                   1062   
1     76           1            46.20         940.05                    901   
2     39           2            43.05         919.62                    928   
3     74           3            23.01         538.68                    479   
4     30           3            38.19         875.93                    650   
..   ...         ...              ...            ...                    ...   
495   76           2            58.12         139.76                    428   
496   76           2            81.67         434.50                    370   
497   24           0            93.68         928.09                    439   
498   43           0            85.05         998.00                    238   
499   54           1            46.16         812.59                   1142   

     gender_Female  gender_Male  marital_status_Married  \
0                0            1                       1   
1                1            0                       0   
2                1            0                       1   
3                1            0                       0   
4                0            1                       1   
..             ...          ...                     ...   
495              1            0                       1   
496              0            1                       0   
497              1            0                       1   
498              0            1                       1   
499              1            0                       1   

     marital_status_Single  contract_type_Monthly  ...  online_backup_No  \
0                        0                      1  ...                 1   
1                        1                      0  ...                 1   
2                        0                      1  ...                 0   
3                        1                      1  ...                 0   
4                        0                      0  ...                 1   
..                     ...                    ...  ...               ...   
495                      0                      0  ...                 1   
496                      1                      1  ...                 1   
497                      0                      0  ...                 1   
498                      0                      0  ...                 1   
499                      0                      0  ...                 1   

     online_backup_Yes  device_protection_No  device_protection_Yes  \
0                    0                     1                      0   
1                    0                     1                      0   
2                    1                     1                      0   
3                    1                     0                      1   
4                    0                     0                      1   
..                 ...                   ...                    ...   
495                  0                     0                      1   
496                  0                     0                      1   
497                  0                     0                      1   
498                  0                     1                      0   
499                  0                     0                      1   

     tech_support_No  tech_support_Yes  streaming_tv_No  streaming_tv_Yes  \
0                  0                 1                0                 1   
1                  0                 1                0                 1   
2                  1                 0                0                 1   
3                  1                 0                1                 0   
4                  1                 0                1                 0   
..               ...               ...              ...               ...   
495                1                 0    

In [11]:
y = df["churn_status"]
y

0      0
1      0
2      0
3      1
4      0
      ..
495    0
496    0
497    0
498    0
499    0
Name: churn_status, Length: 500, dtype: int64

Bifurgating data into training and test data - Train Test Split

In [12]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2)

In [13]:
x_train

age  dependents  monthly_charges  total_charges  call_duration_minutes  \
187   67           3            52.35          68.95                    797   
116   44           0            78.89         865.94                    261   
486   60           2            18.57         865.44                    305   
47    57           2            28.93         773.84                    822   
484   42           3            54.56         141.32                   1109   
..   ...         ...              ...            ...                    ...   
103   72           1            68.58         216.47                    570   
27    49           0            72.47          77.61                   1004   
487   65           1            39.04         837.63                    686   
354   68           2             5.99         166.57                    919   
6     24           0            35.63         200.36                     75   

     gender_Female  gender_Male  marital_status_Married  \
187              0            1                       1   
116              0            1                       0   
486              0            1                       1   
47               1            0                       1   
484              1            0                       1   
..             ...          ...                     ...   
103              1            0                       1   
27               0            1                       0   
487              0            1                       0   
354              0            1                       1   
6                1            0                       0   

     marital_status_Single  contract_type_Monthly  ...  online_backup_No  \
187                      0                      1  ...                 1   
116                      1                      0  ...                 0   
486                      0                      0  ...                 1   
47                       0                      1  ...                 1   
484                      0                      1  ...                 0   
..                     ...                    ...  ...               ...   
103                      0                      0  ...                 0   
27                       1                      1  ...                 1   
487                      1                      0  ...                 0   
354                      0                      0  ...                 0   
6                        1                      1  ...                 1   

     online_backup_Yes  device_protection_No  device_protection_Yes  \
187                  0                     0                      1   
116                  1                     1                      0   
486                  0                     1                      0   
47                   0                     1                      0   
484                  1                     0                      1   
..                 ...                   ...                    ...   
103                  1                     0                      1   
27                   0                     1                      0   
487                  1                     1                      0   
354                  1                     0                      1   
6                    0                     0                      1   

     tech_support_No  tech_support_Yes  streaming_tv_No  streaming_tv_Yes  \
187                0                 1                1                 0   
116                1                 0                0                 1   
486                1                 0                0                 1   
47                 1                 0                1                 0   
484                0                 1                0                 1   
..               ...               ...              ...               ...   
103                1                 0    

# Decision tree classifier

In [14]:
model_dt = DecisionTreeClassifier(criterion ='gini', random_state= 100,max_depth = 6, min_samples_leaf =8)

In [15]:
model_dt.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [16]:
y_pred = model_dt.predict(x_test)

In [17]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [18]:
model_dt.score(x_test,y_test)

0.77

In [19]:
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.81      0.93      0.87        80
           1       0.33      0.15      0.21        20

    accuracy                           0.77       100
   macro avg       0.57      0.54      0.54       100
weighted avg       0.72      0.77      0.73       100



In [20]:
print(confusion_matrix(y_test,y_pred))

[[74  6]
 [17  3]]


As you can see that the accuracy is quite low, and as it's an imbalanced dataset, we shouldn't consider Accuracy as our metrics to measure the model, as Accuracy is cursed in imbalanced datasets.
Hence, we need to check recall, precision & f1 score for the minority class, and it's quite evident that the precision, recall & f1 score is too low for Class 1, i.e. churned customers.
Hence, moving ahead to call SMOTEENN (UpSampling + ENN)

In [21]:
from imblearn.combine import SMOTEENN

In [22]:
sm = SMOTEENN()
x_resampled, y_resampled = sm.fit_resample(x,y)

In [23]:
xr_train,xr_test,yr_train,yr_test=train_test_split(x_resampled, y_resampled,test_size=0.2)

In [24]:
model_dt_smote=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)

In [25]:
model_dt_smote.fit(xr_train,yr_train)
yr_predict = model_dt_smote.predict(xr_test)
model_score_r = model_dt_smote.score(xr_test, yr_test)
print(model_score_r)
print(metrics.classification_report(yr_test, yr_predict))

0.8051948051948052
              precision    recall  f1-score   support

           0       0.82      0.76      0.79        37
           1       0.79      0.85      0.82        40

    accuracy                           0.81        77
   macro avg       0.81      0.80      0.80        77
weighted avg       0.81      0.81      0.80        77



In [26]:
print(metrics.confusion_matrix(yr_test, yr_predict))

[[28  9]
 [ 6 34]]


Now we can see quite better results, i.e. Accuracy: 82 %, and a very good recall, precision & f1 score for minority class.
Let's try with some other classifier.

# Random Forest Classifier

In [27]:
from sklearn.ensemble import RandomForestClassifier

In [28]:
model_rf=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [29]:
model_rf.fit(x_train,y_train)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [30]:
y_pred=model_rf.predict(x_test)

In [31]:
model_rf.score(x_test,y_test)

0.8

In [32]:
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.80      1.00      0.89        80
           1       0.00      0.00      0.00        20

    accuracy                           0.80       100
   macro avg       0.40      0.50      0.44       100
weighted avg       0.64      0.80      0.71       100



C:\Users\ragha\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ragha\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ragha\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [33]:
sm = SMOTEENN()
X_resampled1, y_resampled1 = sm.fit_resample(x,y)

In [34]:
xr_train1,xr_test1,yr_train1,yr_test1=train_test_split(X_resampled1, y_resampled1,test_size=0.2)

In [35]:
model_rf_smote=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [36]:
model_rf_smote.fit(xr_train1,yr_train1)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [37]:
yr_predict1 = model_rf_smote.predict(xr_test1)

In [38]:
model_score_r1 = model_rf_smote.score(xr_test1, yr_test1)

In [39]:
print(model_score_r1)
print(metrics.classification_report(yr_test1, yr_predict1))

0.7926829268292683
              precision    recall  f1-score   support

           0       0.77      0.70      0.73        33
           1       0.81      0.86      0.83        49

    accuracy                           0.79        82
   macro avg       0.79      0.78      0.78        82
weighted avg       0.79      0.79      0.79        82



In [40]:
print(metrics.confusion_matrix(yr_test1, yr_predict1))

[[23 10]
 [ 7 42]]


With RF Classifier, also we are able to get quite good results, infact better than Decision Tree.
We can now further go ahead and create multiple classifiers to see how the model performance is and then compare that with RF and DTC.

# Performing PCA 

In [41]:
# Applying PCA
from sklearn.decomposition import PCA
pca = PCA(0.9)
xr_train_pca = pca.fit_transform(xr_train1)
xr_test_pca = pca.transform(xr_test1)
explained_variance = pca.explained_variance_ratio_

In [42]:
model=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [43]:
model.fit(xr_train_pca,yr_train1)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [44]:
yr_predict_pca = model.predict(xr_test_pca)

In [45]:
model_score_r_pca = model.score(xr_test_pca, yr_test1)

In [46]:
print(model_score_r_pca)
print(metrics.classification_report(yr_test1, yr_predict_pca))

0.8170731707317073
              precision    recall  f1-score   support

           0       0.78      0.76      0.77        33
           1       0.84      0.86      0.85        49

    accuracy                           0.82        82
   macro avg       0.81      0.81      0.81        82
weighted avg       0.82      0.82      0.82        82



With PCA, couldn't see any better results, hence the model which was created by RF Classifier, was the best when compared to DTC and PCA.

# LOGISTIC REGRESSION FOR RESAMPLED DATA

In [47]:
from sklearn.linear_model import LogisticRegression

In [48]:
model_LR = LogisticRegression(solver='liblinear', random_state=1)
model_LR.fit(xr_train,yr_train)

LogisticRegression(random_state=1, solver='liblinear')

In [49]:
yLR_predict = model_LR.predict(xr_test1)

In [50]:
yLR_predict

array([0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1], dtype=int64)

In [51]:
model_score_r_LR = model_LR.score(xr_test1, yr_test1)

In [52]:
print(model_score_r_LR)

0.8292682926829268


In [53]:
print(metrics.classification_report(yr_test1, yLR_predict))

              precision    recall  f1-score   support

           0       0.74      0.88      0.81        33
           1       0.91      0.80      0.85        49

    accuracy                           0.83        82
   macro avg       0.83      0.84      0.83        82
weighted avg       0.84      0.83      0.83        82



Logistic model done using SMOTEENN re-sampled data, outperformed RF Classifier when compared with precision anf f-1 score , whereas accuracy remains same.
The finalised model is Logistic Regression with SMOTEENN(re-sampled data), is now ready and dumped as model.sav

# Making a Predictive System

Glancing quickly how the model works!!

In [54]:
import numpy as np

In [56]:
# inputdata = ('age, dependent, monthly_charges, total_charges, call_duration_minutes, gender_Female, gender_Male, marital_status))
input_data = (60, 1,67.82, 304.67, 1,0,0,1,0,1,0,1,0,1,0,1,1,0,0,1,0,1,0,1,1,0,0,1,1)
#Changing inout to numoy array 
input_data_as_numpy_array = np.asarray(input_data)

#reshaping the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model_LR.predict(input_data_reshaped)
print(prediction)

if(prediction[0]==0):
 print('The person is likely to Continue!')
else:
 print('The person is likely to be churned ')    


[0]
The person is likely to Continue!


C:\Users\ragha\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


Pickling the model

In [ ]:
import pickle

In [ ]:
filename = 'model.sav'

In [ ]:
pickle.dump(model_LR, open(filename, 'wb'))

In [ ]:
#Loaded the saved model
load_model = pickle.load(open('model.sav', 'rb'))

In [ ]:
model_score_r_LR = load_model.score(xr_test1, yr_test1)

In [ ]:
model_score_r_LR

Our final model i.e. Logistic Regression with SMOTEENN displays 82.2% of accuracy score which is far better than DTC, RF, PCA altogether , is now ready and dumped in model.sav